name: dougburrier
favicon: null
layout_spectrum: 0.49998
typography_spectrum: 0.28073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff5f8'
    - '#181816'
    - '#ff8f00'
    - '#b9beb4'
    - '#a94c00'
  brandStrength: 0.8486555011477321
  lightness: 0.4050616801250726
  saturation: 0.8946140347979963
  rhythmicContrast: 0.25
purpose: []
